[build]
  command = "cd vite-project && npm run build"
  publish = "vite-project/dist"
  base = "vite-project"
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
